### ISSUE TITLE
This ain't a hello-world. No Code!

### ISSUE THREAD

**Issue by Nirmal4G** [MadsTorgersen/hello-world#3]
You want Issues? Here's one...

Problem:
Your repo does not have any code... 🤔

Repro:
Clone the repo
Open in explorer
See an almost empty folder with only readme 😭

Please fix the issue... 😋

**Comment by Nirmal4G** [comment]
@MadsTorgersen Please look into it.

**Comment by MadsTorgersen** [comment]
That did the trick, thanks!

And thanks for helping me test my email settings - it seems that they work well. :-)

**Comment by Nirmal4G** [comment]
No Problem...!
